apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-hub-bop-settlements-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reporting-hub-bop-settlements-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reporting-hub-bop-settlements-ui
    spec:
      containers:
      - name: app
        image: ghcr.io/mojaloop/reporting-hub-bop-settlements-ui:v0.0.0
        ports:
        - containerPort: 8083
        env:
          - name: CENTRAL_SETTLEMENTS_ENDPOINT
            value: /api/settlement/v2
          - name: CENTRAL_LEDGER_ENDPOINT
            value: /api/ledger
          - name: REPORTING_API_ENDPOINT
            value: /api/reporting
