apiVersion: v1
kind: Service
metadata:
  name: reporting-hub-bop-settlements-ui
  labels:
    app.kubernetes.io/name: reporting-hub-bop-settlements-ui
spec:
  ports:
  - port: 80
    targetPort: 8083
    name: http
  selector:
    app.kubernetes.io/name: reporting-hub-bop-settlements-ui
